### ISSUE TITLE
UI process crash in wl_interface_equal()

### ISSUE THREAD

**Issue by mcatanzaro** [Igalia/WPEBackend-fdo#102]
Random crash:

```
Core was generated by `epiphany'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f5b9c7e1d10 in wl_interface_equal (a=0x332f3835313336, 
    b=<optimized out>) at ../src/wayland-util.c:166
166		return a == b || strcmp(a->name, b->name) == 0;
```

```
(gdb) bt full
#0  0x00007f5b9c7e1d10 in wl_interface_equal (a=0x332f3835313336, b=<optimized out>) at ../src/wayland-util.c:166
#1  0x00007f5b9c7e1016 in wl_closure_lookup_objects
    (closure=closure@entry=0x55a12277ff10, objects=objects@entry=0x55a110d289c0) at ../src/connection.c:911
        object = <optimized out>
        message = 0x7f5b9d6b9098 <wl_surface_requests+24>
        signature = 0x7f5b9d6b5504 "ii"
        arg = {type = 111 'o', nullable = 1}
        i = 0
        count = <optimized out>
        id = 8
#2  0x00007f5b9c7ddd5b in wl_client_connection_data (fd=<optimized out>, mask=<optimized out>, data=0x55a110d28990)
    at ../src/wayland-server.c:413
        client = 0x55a110d28990
        connection = 0x55a110e15000
        resource = 0x55a116183c00
        object = 0x55a116183c00
        closure = 0x55a12277ff10
        message = 0x7f5b9d6b9098 <wl_surface_requests+24>
        p = {13, 1310721}
        resource_flags = <optimized out>
        opcode = 1
        size = <optimized out>
        since = <optimized out>
        len = <optimized out>
#3  0x00007f5b9c7df3ca in wl_event_loop_dispatch (loop=0x55a10fbef010, timeout=timeout@entry=-1)
    at ../src/event-loop.c:641
        ep = 
              {{events = 1, data = {ptr = 0x7f5b8c05e440, fd = -1945770944, u32 = 2349196352, u64 = 140031167947840}}, {events = 32766, data = {ptr = 0x55a12277ff28, fd = 578289448, u32 = 578289448, u64 = 94150556385064}}, {events = 0, data = {ptr = 0x4000000000000000, fd = 0, u32 = 0, u64 = 4611686018427387904}}, {events = 21921, data = {ptr = 0x7f5b9d6b2455 <wl_closure_clear_fds+53>, fd = -1653922731, u32 = 2641044565, u64 = 140031459796053}}, {events = 2641075061, data = {ptr = 0xfbd1ae0000000000, fd = 0, u32 = 0, u64 = 18145475688675672064}}, {events = 3314788412, data = {ptr = 0x1, fd = 1, u32 = 1, u64 = 1}}, {events = 2641045038, data = {ptr = 0x1800007f5b, fd = 32603, u32 = 32603, u64 = 103079247707}}, {events = 48, data = {ptr = 0x55a10f88ed30, fd = 260631856, u32 = 260631856, u64 = 94150238727472}}, {events = 260631856, data = {ptr = 0x9d6b24dd000055a1, fd = 21921, u32 = 21921, u64 = 11343200618069120417}}, {events = 32603, data = {ptr = 0xf88ee75, fd = 260632181, u32 = 260632181, u64 = 260632181}}, {events = 4224822784, data = {ptr = 0x2277ffecc593a83c, fd = -980178884, u32 = 3314788412, u64 = 2483735111910271036}}, {events = 21921, data = {ptr = 0x7ffe41af9750, fd = 1102026576, u32 = 1102026576, u64 = 140730000447312}}, {events = 2641059627, data = {ptr = 0xfbd1ae0000007f5b, fd = 32603, u32 = 32603, u64 = 18145475688675704667}}, {events = 3314788412, data = {ptr = 0x55a12277ff10, fd = 578289424, u32 = 578289424, u64 = 94150556385040}}, {events = 261207904, data = {ptr = 0xf91b760000055a1, fd = 21921, u32 = 21921, u64 = 1121879405136729505}}, {events = 21921, data = {ptr = 0xc593a83cfbd1ae00, fd = -70144512, u32 = 4224822784, u64 = 14236907826924596736}}, {events = 2147483647, data = {ptr = 0xf91b76000000000, fd = 0, u32 = 0, u64 = 1121879405136707584}}, {events = 21921, data = {ptr = 0x55a10f91be00, fd = 261209600, u32 = 261209600, u64 = 94150239305216}}, {events = 2, data = {ptr = 0x7fffffff00000000, fd = 0, u32 = 0, u64 = 9223372032559808512}}, {events = 0, data = {ptr = 0x55a10f8a73b0, fd = 260731824, u32 = 260731824, u64 = 94150238827440}}, {events = 1102026868, data = {ptr = 0x9c3a6b2100007ffe, fd = 32766, u32 = 32766, u64 = 11257428008044101630}}, {events = 32603, data = {ptr = 0x55a12277ff30, fd = 578289456, u32 = 578289456, u64 = 94150556385072}}, {events = 4224822784, data = {ptr = 0x1c593a83c, fd = -980178884, u32 = 3314788412, u64 = 7609755708}}, {events = 0, data = {ptr = 0x7ffe41af9878, fd = 1102026872, u32 = 1102026872, u64 = 140730000447608}}, {events = 1, data = {ptr = 0x41af981000000000, fd = 0, u32 = 0, u64 = 4733168927876579328}}, {events = 32766, data = {ptr = 0x7ffe41af97e0, fd = 1102026720, u32 = 1102026720, u64 = 140730000447456}}, {events = 1102133416, data = {ptr = 0x41af981000007ffe, fd = 32766, u32 = 32766, u64 = 4733168927876612094}}, {events = 32766, data = {ptr = 0x7fffffff, fd = 2147483647, u32 = 2147483647, u64 = 2147483647}}, {events = 1, data = {ptr = 0xa338986b00000000, fd = 0, u32 = 0, u64 = 11761318012206972928}}, {events = 32603, data = {ptr = 0x1, fd = 1, u32 = 1, u64 = 1}}, {events = 260731824, data = {ptr = 0x55a1, fd = 21921, u32 = 21921, u64 = 21921}}, {events = 0, data = {ptr --Type <RET> for more, q to quit, c to continue without paging--c
= 0x7ffe41af9880, fd = 1102026880, u32 = 1102026880, u64 = 140730000447616}}}
        source = <optimized out>
        i = <optimized out>
        count = <optimized out>
#4  0x00007f5b9d4a0596 in WS::ServerSource::<lambda(GSource*, GSourceFunc, gpointer)>::operator() (__closure=0x0, base=0x55a10fc0c6f0) at ../src/ws.cpp:114
        eventLoop = <optimized out>
        source = @0x55a10fc0c6f0: {static s_sourceFuncs = {prepare = 0x7f5b9d4a04b0 <WS::ServerSource::<lambda(GSource*, gint*)>::_FUN(GSource *, gint *)>, check = 0x7f5b9d4a03f0 <WS::ServerSource::<lambda(GSource*)>::_FUN(GSource *)>, dispatch = 0x7f5b9d4a0550 <WS::ServerSource::<lambda(GSource*, GSourceFunc, gpointer)>::_FUN(GSource *, GSourceFunc, gpointer)>, finalize = 0x0, closure_callback = 0x0, closure_marshal = 0x0}, source = {callback_data = 0x0, callback_funcs = 0x0, source_funcs = 0x7f5b9d4a7260 <WS::ServerSource::s_sourceFuncs>, ref_count = 3, context = 0x55a10f8a73b0, priority = 0, flags = 35, source_id = 16, poll_fds = 0x55a10f97fa60 = {0x55a10fc0c750}, prev = 0x55a10f99ae10, next = 0x55a10fd3c600, name = 0x55a10f8fca00 "WPEBackend-fdo::Host", priv = 0x55a10fa7dd90}, pfd = {fd = 18, events = 25, revents = 1}, display = 0x55a10f857b20}
#5  0x00007f5b9d4a0596 in WS::ServerSource::<lambda(GSource*, GSourceFunc, gpointer)>::_FUN(GSource *, GSourceFunc, gpointer) () at ../src/ws.cpp:123
#6  0x00007f5ba367fd0d in g_main_dispatch (context=0x55a10f8a73b0) at ../glib/gmain.c:3309
        dispatch = 0x7f5b9d4a0550 <WS::ServerSource::<lambda(GSource*, GSourceFunc, gpointer)>::_FUN(GSource *, GSourceFunc, gpointer)>
        prev_source = 0x0
        was_in_call = 0
        user_data = 0x0
        callback = 0x0
        cb_funcs = 0x0
        cb_data = <optimized out>
        need_destroy = <optimized out>
        source = 0x55a10fc0c6f0
        current = 0x55a10f8b1300
        i = 0
        __func__ = "g_main_dispatch"
#7  0x00007f5ba367fd0d in g_main_context_dispatch (context=context@entry=0x55a10f8a73b0) at ../glib/gmain.c:3974
#8  0x00007f5ba367ff90 in g_main_context_iterate (context=context@entry=0x55a10f8a73b0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/gmain.c:4047
        max_priority = 2147483647
        timeout = 40612
        some_ready = 1
        nfds = <optimized out>
        allocated_nfds = <optimized out>
        fds = 0x55a11ac68750
#9  0x00007f5ba3680033 in g_main_context_iteration (context=context@entry=0x55a10f8a73b0, may_block=may_block@entry=1) at ../glib/gmain.c:4108
        retval = <optimized out>
#10 0x00007f5ba389ee95 in g_application_run (application=0x55a10f89e720 [EphyShell], argc=<optimized out>, argv=<optimized out>) at ../gio/gapplication.c:2559
        arguments = 0x55a10f98fac0
        status = 0
        context = 0x55a10f8a73b0
        acquired_context = 1
        __func__ = "g_application_run"
#11 0x000055a10daab105 in main (argc=1, argv=0x7ffe41af9b78) at ../src/ephy-main.c:427
        option_context = 0x55a10f85e780
        option_group = 0x55a10f85e800
        error = 0x0
        user_time = 109215
        arbitrary_url = 0
        ctx = 0x55a10f9be6d0
        mode = EPHY_EMBED_SHELL_MODE_BROWSER
        status = 91
        flags = EPHY_FILE_HELPERS_ENSURE_EXISTS
        desktop_info = 0x0
```

**Comment by aperezdc** [comment]
@mcatanzaro I assume that the radio silence means you don't have come across a good way to reproduce this reliably, right? I have yet to see this one myself 🕵️

I have moved the goalpost for this to the 1.8.0 milestone, given that 1.6.0 is already out.

**Comment by mcatanzaro** [comment]
I don't know how to reproduce it. It's very rare that I find a reproducer for a WebKit-related crash. :( I normally rely on code inspection to fix reported crashes.

**Comment by mcatanzaro** [comment]
Closing this, I haven't seen it since March and my RAM was flipping bits at the time, could have easily been a hardware problem.
